<?php

$DB_HOST = "mysql";
$DB_USERNAME = "kaum";
$DB_PASSWORD = "Tc7kU7HKzkC9N4/m";
$DB_NAME = "kaum";

/*

CREATE USER 'kaum'@'%' IDENTIFIED VIA mysql_native_password USING '***';
GRANT USAGE ON *.* TO 'kaum'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `kaum`;
GRANT ALL PRIVILEGES ON `kaum`.* TO 'kaum'@'%';

*/

